spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://niotneot.cnodnbvune1u.us-east-1.rds.amazonaws.com:3306/mjko?serverTimezone=Asia/Seoul
    username: manager
    password: manager33
  jpa:
    open-in-view: true
    hibernate:
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #JPA가 사용하는 기본 넘버링 전략을 따라가지 않는다
    show-sql: true
    properties:
      hibernate.format_sql: true
#      hibernate.hbm2ddl.auto: update
  
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

#Gson HTTP Message Converter 설정
#spring.http.converters.preferred-json-mapper=gson #Spring Boot Version < 2.3.0 RELEASE
#  mvc:
#    converters:
#      preferred-json-mapper: gson  #Spring Boot Version >= 2.3.0 RELEASE  
      
  

#  jackson:
#    serialization:
#      fail-on-empty-beans: false

mybatis:
  type-aliases-package: com.sist.nono.dto, com.sist.nono.paging # 매핑할 모델의 패키지 경로 (mybatis 매핑 type을 짧게 쓰기 위한 설정)
  mapper-locations: classpath:mappers/*.xml # mapper.xml 위치 명시



logging:
  level:
   org:
     hibernate:
       type:
         descriptor:
           sql:
             BasicBinder: trace
      
---
sist:
  key: sist1234
      
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
